name: dress_up_game
description: A character customization game using Flutter and Flame

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: 1.18.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/metadata.json
    - assets/images/
    - assets/images/expression/
    - assets/images/blush/
    - assets/images/ahoge/
    - assets/images/costume/
    - assets/images/accessories_front/
    - assets/images/hand_gesture/
    - assets/images/hair_front/
    - assets/images/hair_front/curl/
    - assets/images/hair_front/hime_cut/
    - assets/images/hair_front/hime_cut_short/
    - assets/images/hair_front/long/
    - assets/images/hair_front/middle_part/
    - assets/images/hair_front/short/
    - assets/images/hair_front/short_bob/
    - assets/images/hair_front/side/
    - assets/images/hair_behind/
    - assets/images/hair_behind/twintail_3/
    - assets/images/hair_behind/twin_tail/
    - assets/images/hair_behind/twin_tail_2/
    - assets/images/hair_behind/short_hair/
    - assets/images/hair_behind/short_hair_2/
    - assets/images/hair_behind/short_curly/
    - assets/images/hair_behind/short_bob/
    - assets/images/hair_behind/long_hair_hime_cut/
    - assets/images/hair_behind/long_curl/
